services:

  backend:
    build:
      context: .  
      dockerfile: Dockerfile_backend  
      target: backend  
    image: fransbudiman/quirknotes_backend:latest  
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb

  frontend:
    build:
      context: . 
      dockerfile: Dockerfile_frontend 
      target: frontend  
    image: fransbudiman/quirknotes_frontend:latest  
    ports:
      - "3000:80"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"